# Generated by Django 6.0.4 on 2026-04-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('field', models.CharField(choices=[('temperature_out', 'Temperatura exterior (°C)'), ('temperature_in', 'Temperatura interior (°C)'), ('humidity_out', 'Humedad exterior (%)'), ('humidity_in', 'Humedad interior (%)'), ('pressure', 'Presión (hPa)'), ('wind_speed', 'Velocidad del viento (km/h)'), ('wind_gust', 'Ráfaga de viento (km/h)'), ('rain_rate', 'Tasa de lluvia (mm/h)'), ('rain_daily', 'Lluvia diaria (mm)'), ('uv_index', 'Índice UV')], max_length=32)),
                ('operator', models.CharField(choices=[('gt', 'Mayor que (>)'), ('lt', 'Menor que (<)'), ('gte', 'Mayor o igual (>=)'), ('lte', 'Menor o igual (<=)')], max_length=4)),
                ('threshold', models.FloatField()),
                ('email_to', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
