# Generated by Django 6.0.4 on 2026-04-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(db_index=True, max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('temperature_out', models.FloatField(blank=True, null=True)),
                ('temperature_in', models.FloatField(blank=True, null=True)),
                ('humidity_out', models.FloatField(blank=True, null=True)),
                ('humidity_in', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_gust', models.FloatField(blank=True, null=True)),
                ('wind_dir', models.FloatField(blank=True, null=True)),
                ('rain_rate', models.FloatField(blank=True, null=True)),
                ('rain_daily', models.FloatField(blank=True, null=True)),
                ('uv_index', models.FloatField(blank=True, null=True)),
                ('solar_radiation', models.FloatField(blank=True, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['station_id', 'received_at'], name='ingest_weat_station_333f05_idx')],
            },
        ),
    ]
